name: Cargo Check
on:
  workflow_call:

jobs:
  cargo_check:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Setup | Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32

      - name: Build | Check
        run: cargo check --workspace --locked || true
